services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    container_name: authors-api
    restart: always
    volumes:
      - .:/app:z
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/mediafiles
    expose:
      - 8000
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgresql
    depends_on:
      - postgres
      - mailhog
    command: /start.sh
    networks:
      - authors-api

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgresql/Dockerfile
    container_name: authors-postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgresql
    networks:
      - authors-api

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: authors-mailhog
    ports:
      - 8025:8025
    networks:
      - authors-api

  nginx:
    build:
      context: ./docker/local/nginx/
      dockerfile: Dockerfile
    container_name: authors-nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - api
    volumes:
      - static_volume:/app/src/staticfiles
      - static_volume:/app/src/mediafiles
    networks:
      - authors-api

networks:
  authors-api:
    driver: bridge

volumes:
      static_volume:
      media_volume:
      local_postgres_data: {}
      local_postgres_data_backups: {}
